apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: infras
spec:
  interval: 1h
  timeout: 10m
  releaseName: mysql
  targetNamespace: infras
  chart:
    spec:
      chart: mysql
      version: 14.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
        namespace: infras
  values:
    image:
      registry: docker.io
      repository: bitnamilegacy/mysql
      tag: 9.4.0-debian-12-r1
    architecture: standalone
    auth:
      createDatabase: false
      # database: order_system
      username: "admin"
      existingSecret: mysql-secrets
    primary:
      persistence: { enabled: true, size: 5Gi, storageClass: standard }
      resources:
        requests: { cpu: 2000m, memory: 2048Mi }
        limits: { cpu: 2000m, memory: 2048Mi }
      startupProbe:
        failureThreshold: 120
    # secondary:
    #   replicaCount: 1
    #   persistence: { enabled: true, size: 3Gi, storageClass: standard }
    #   resources:
    #     requests: { cpu: 100m, memory: 1024Mi }
    #     limits: { cpu: 100m, memory: 1024Mi }
    #   startupProbe:
    #     failureThreshold: 120
    metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnamilegacy/mysqld-exporter
        tag: 0.17.2-debian-12-r16
      resources:
        requests: { cpu: 100m, memory: 128Mi }
        limits: { cpu: 100m, memory: 128Mi }
      serviceMonitor:
        enabled: true
        jobLabel: "mysql"
        interval: 30s
        scrapeTimeout: 30s
      extraArgs:
        primary:
          ## - --collect.global_status
          ## - --collect.global_variables
          ## - --collect.engine_innodb_status
          ## - --collect.binlog_size
          ## - --collect.info_schema.clientstats
          ## - --collect.info_schema.innodb_metrics
          ## - --collect.info_schema.innodb_tablespaces
          ## - --collect.info_schema.query_response_time
          ## - --collect.info_schema.tables
          ## - --collect.info_schema.tables.databases
          ## - --collect.info_schema.tablestats
          ## - --collect.perf_schema.file_events
          ## - --collect.perf_schema.file_instances
          ## - --collect.perf_schema.indexiowaits
          ## - --collect.perf_schema.tableiowaits
          ## - --collect.perf_schema.tablelocks