export const users = [
  {
    "first_name": "Emma",
    "last_name": "Johnson",
    "address_1": "123 Main Street",
    "address_2": "Suite 4B",
    "city": "New York",
    "state": "NY",
    "postcode": "10001",
    "country": "US",
    "email": "emma.johnson@example.com",
    "phone": "(212) 555-0123"
  },
  {
    "first_name": "James",
    "last_name": "Smith",
    "address_1": "456 Oak Avenue",
    "address_2": "",
    "city": "Los Angeles",
    "state": "CA",
    "postcode": "90001",
    "country": "US",
    "email": "james.smith@example.com",
    "phone": "(213) 555-2345"
  },
  {
    "first_name": "Sophia",
    "last_name": "Williams",
    "address_1": "789 Pine Road",
    "address_2": "Apt 3C",
    "city": "Chicago",
    "state": "IL",
    "postcode": "60601",
    "country": "US",
    "email": "sophia.williams@example.com",
    "phone": "(312) 555-4567"
  },
  {
    "first_name": "Michael",
    "last_name": "Brown",
    "address_1": "101 Maple Drive",
    "address_2": "",
    "city": "Houston",
    "state": "TX",
    "postcode": "77001",
    "country": "US",
    "email": "michael.brown@example.com",
    "phone": "(713) 555-6789"
  },
  {
    "first_name": "Olivia",
    "last_name": "Jones",
    "address_1": "202 Cedar Lane",
    "address_2": "Unit 12",
    "city": "Phoenix",
    "state": "AZ",
    "postcode": "85001",
    "country": "US",
    "email": "olivia.jones@example.com",
    "phone": "(602) 555-8901"
  },
  {
    "first_name": "William",
    "last_name": "Garcia",
    "address_1": "303 Elm Street",
    "address_2": "",
    "city": "Philadelphia",
    "state": "PA",
    "postcode": "19101",
    "country": "US",
    "email": "william.garcia@example.com",
    "phone": "(215) 555-2346"
  },
  {
    "first_name": "Ava",
    "last_name": "Miller",
    "address_1": "404 Birch Boulevard",
    "address_2": "Floor 5",
    "city": "San Antonio",
    "state": "TX",
    "postcode": "78201",
    "country": "US",
    "email": "ava.miller@example.com",
    "phone": "(210) 555-3457"
  },
  {
    "first_name": "Benjamin",
    "last_name": "Davis",
    "address_1": "505 Walnut Street",
    "address_2": "Apt 7D",
    "city": "San Diego",
    "state": "CA",
    "postcode": "92101",
    "country": "US",
    "email": "benjamin.davis@example.com",
    "phone": "(619) 555-4568"
  },
  {
    "first_name": "Isabella",
    "last_name": "Rodriguez",
    "address_1": "606 Ash Avenue",
    "address_2": "",
    "city": "Dallas",
    "state": "TX",
    "postcode": "75201",
    "country": "US",
    "email": "isabella.rodriguez@example.com",
    "phone": "(214) 555-5679"
  },
  {
    "first_name": "Ethan",
    "last_name": "Martinez",
    "address_1": "707 Spruce Court",
    "address_2": "Suite 9A",
    "city": "San Jose",
    "state": "CA",
    "postcode": "95101",
    "country": "US",
    "email": "ethan.martinez@example.com",
    "phone": "(408) 555-6780"
  },
  {
    "first_name": "Mia",
    "last_name": "Wilson",
    "address_1": "808 Redwood Way",
    "address_2": "",
    "city": "Austin",
    "state": "TX",
    "postcode": "78701",
    "country": "US",
    "email": "mia.wilson@example.com",
    "phone": "(512) 555-7891"
  },
  {
    "first_name": "Alexander",
    "last_name": "Anderson",
    "address_1": "909 Magnolia Drive",
    "address_2": "Apt 2F",
    "city": "Jacksonville",
    "state": "FL",
    "postcode": "32201",
    "country": "US",
    "email": "alexander.anderson@example.com",
    "phone": "(904) 555-8902"
  },
  {
    "first_name": "Charlotte",
    "last_name": "Taylor",
    "address_1": "1010 Poplar Lane",
    "address_2": "",
    "city": "Fort Worth",
    "state": "TX",
    "postcode": "76101",
    "country": "US",
    "email": "charlotte.taylor@example.com",
    "phone": "(817) 555-9013"
  },
  {
    "first_name": "Daniel",
    "last_name": "Thomas",
    "address_1": "1111 Cypress Road",
    "address_2": "Unit 8B",
    "city": "Columbus",
    "state": "OH",
    "postcode": "43201",
    "country": "US",
    "email": "daniel.thomas@example.com",
    "phone": "(614) 555-1234"
  },
  {
    "first_name": "Amelia",
    "last_name": "Moore",
    "address_1": "1212 Willow Street",
    "address_2": "",
    "city": "Charlotte",
    "state": "NC",
    "postcode": "28201",
    "country": "US",
    "email": "amelia.moore@example.com",
    "phone": "(704) 555-2345"
  }
]